#!/usr/bin/env bash
# Source this file on the server before running Alpamayo scripts:
#   source scripts/server_env.sh

set -euo pipefail

export FAITHFUL_ALPAMAYO_PROJECT_ROOT="/dss/dssfs05/pn39qo/pn39qo-dss-0001/di97fer/projects_for_test/Faithful-Alpamayo-1.5"
export FAITHFUL_ALPAMAYO_SHARED_HF_HOME="/dss/dssfs05/pn39qo/pn39qo-dss-0001/huggingface"
export FAITHFUL_ALPAMAYO_DATA_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/data"
export FAITHFUL_ALPAMAYO_MODELS_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/models"
export FAITHFUL_ALPAMAYO_OUTPUTS_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/outputs"
export FAITHFUL_ALPAMAYO_CHECKPOINTS_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/checkpoints"
export FAITHFUL_ALPAMAYO_ADAPTERS_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/adapters"
export FAITHFUL_ALPAMAYO_LOGS_ROOT="${FAITHFUL_ALPAMAYO_PROJECT_ROOT}/logs"

# Model, processor, and HF dataset hub cache already exist on this filesystem.
# Keep this shared cache as the default to avoid re-downloading large repos.
export HF_HOME="${FAITHFUL_ALPAMAYO_SHARED_HF_HOME}"
export HF_HUB_CACHE="${FAITHFUL_ALPAMAYO_SHARED_HF_HOME}/hub"
export HF_XET_CACHE="${FAITHFUL_ALPAMAYO_SHARED_HF_HOME}/xet"
export HF_XET_NUM_CONCURRENT_RANGE_GETS="${HF_XET_NUM_CONCURRENT_RANGE_GETS:-2}"
export HF_HUB_DOWNLOAD_TIMEOUT="${HF_HUB_DOWNLOAD_TIMEOUT:-120}"
export HF_HUB_ETAG_TIMEOUT="${HF_HUB_ETAG_TIMEOUT:-30}"
export HF_HUB_DISABLE_PROGRESS_BARS="${HF_HUB_DISABLE_PROGRESS_BARS:-1}"

# Dataset cache and downloaded PhysicalAI-AV chunks stay under data/.
export HF_DATASETS_CACHE="${FAITHFUL_ALPAMAYO_DATA_ROOT}/hf_datasets_cache"
export PHYSICAL_AI_AV_CACHE_DIR="${FAITHFUL_ALPAMAYO_DATA_ROOT}/physical_ai_av/cache"
export PHYSICAL_AI_AV_LOCAL_DIR="${FAITHFUL_ALPAMAYO_DATA_ROOT}/physical_ai_av/local"

# Non-model generated assets, logs, checkpoints, and adapters have their own roots.
export HF_ASSETS_CACHE="${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/hf_assets_cache"

mkdir -p \
  "${HF_DATASETS_CACHE}" \
  "${HF_ASSETS_CACHE}" \
  "${PHYSICAL_AI_AV_CACHE_DIR}" \
  "${PHYSICAL_AI_AV_LOCAL_DIR}" \
  "${FAITHFUL_ALPAMAYO_DATA_ROOT}/clips" \
  "${FAITHFUL_ALPAMAYO_DATA_ROOT}/manifests" \
  "${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/baseline" \
  "${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/lora" \
  "${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/metrics" \
  "${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/figures" \
  "${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}/qualitative_cases" \
  "${FAITHFUL_ALPAMAYO_CHECKPOINTS_ROOT}/lora" \
  "${FAITHFUL_ALPAMAYO_ADAPTERS_ROOT}/lora" \
  "${FAITHFUL_ALPAMAYO_LOGS_ROOT}"

echo "FAITHFUL_ALPAMAYO_PROJECT_ROOT=${FAITHFUL_ALPAMAYO_PROJECT_ROOT}"
echo "FAITHFUL_ALPAMAYO_DATA_ROOT=${FAITHFUL_ALPAMAYO_DATA_ROOT}"
echo "FAITHFUL_ALPAMAYO_MODELS_ROOT=${FAITHFUL_ALPAMAYO_MODELS_ROOT}"
echo "FAITHFUL_ALPAMAYO_OUTPUTS_ROOT=${FAITHFUL_ALPAMAYO_OUTPUTS_ROOT}"
echo "HF_HOME=${HF_HOME}"
echo "HF_HUB_CACHE=${HF_HUB_CACHE}"
echo "HF_XET_NUM_CONCURRENT_RANGE_GETS=${HF_XET_NUM_CONCURRENT_RANGE_GETS}"
echo "PHYSICAL_AI_AV_CACHE_DIR=${PHYSICAL_AI_AV_CACHE_DIR}"
